# This is a basic workflow to help you get started with Actions

name: Deploye Website

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # It will create a VM of ubuntu-latest and create an instance there
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # actions/checkout will take access of your repo of github and apply following steps on VM
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell. To run our first project we have to install node
      - name: Installing Node
        uses: actions/setup-node@v2-beta  # This is by-default option available in gitHub to install node
        with: 
          node-version: 12

      # Runs a set of commands using the runners shell
      - name: Installing Surge
        run: npm install --global surge

      - name: Deploy using Surge
        run: surge ./ bootcamp2020-asad.surge.sh --token ${{ secrets.SURGE_TOKEN }}
        # ./ means issi directory ki root director pr index.html file utha lo.
